/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lynarstudios_ls_std_time_systemtime_SystemTimeJni */

#ifndef _Included_com_lynarstudios_ls_std_time_systemtime_SystemTimeJni
#define _Included_com_lynarstudios_ls_std_time_systemtime_SystemTimeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lynarstudios_ls_std_time_systemtime_SystemTimeJni
 * Method:    set
 * Signature: (Lcom/lynarstudios/ls/std/time/systemtime/DateParameter;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_lynarstudios_ls_std_time_systemtime_SystemTimeJni_set
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
